// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Q-DXfzsTai-DICv0-F4tBxDykrbuQIM',
    appId: '1:150311313760:web:422f679b1c0e8d8e39fe05',
    messagingSenderId: '150311313760',
    projectId: 'smart-vaccin',
    authDomain: 'smart-vaccin.firebaseapp.com',
    storageBucket: 'smart-vaccin.appspot.com',
    measurementId: 'G-ECN0PVLDW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBE7NzxANyhIFZ19zwe_RAJVoBE-gwrlc',
    appId: '1:150311313760:android:dee6c52ec0d2de0d39fe05',
    messagingSenderId: '150311313760',
    projectId: 'smart-vaccin',
    storageBucket: 'smart-vaccin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmhXeshjZmCnV_qToQKuhIfUya4dMtyPQ',
    appId: '1:150311313760:ios:2631c85f22a7a05139fe05',
    messagingSenderId: '150311313760',
    projectId: 'smart-vaccin',
    storageBucket: 'smart-vaccin.appspot.com',
    iosBundleId: 'georges.com.smartvaccin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmhXeshjZmCnV_qToQKuhIfUya4dMtyPQ',
    appId: '1:150311313760:ios:2631c85f22a7a05139fe05',
    messagingSenderId: '150311313760',
    projectId: 'smart-vaccin',
    storageBucket: 'smart-vaccin.appspot.com',
    iosBundleId: 'georges.com.smartvaccin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1Q-DXfzsTai-DICv0-F4tBxDykrbuQIM',
    appId: '1:150311313760:web:be0b864ae553c7db39fe05',
    messagingSenderId: '150311313760',
    projectId: 'smart-vaccin',
    authDomain: 'smart-vaccin.firebaseapp.com',
    storageBucket: 'smart-vaccin.appspot.com',
    measurementId: 'G-DTMHBRGWEX',
  );
}
